fixes
mirpulatov/made2019_algo pull request #1
Opened 2019-12-03 15:03 UTC by mirpulatov

2019-12-05 00:50 UTC, ylyubimov commented
Когда будешь готов, призови меня в ревью. И указывай успешную посылку контеста + свое ФИО

2019-12-05 00:50 UTC, ylyubimov commented
Все фамилию необязательно) Я тебя узнал)

2019-12-05 00:51 UTC, ylyubimov commented
Но ссылку жду, в description'ах к ПР

2019-12-05 21:33 UTC, ylyubimov requested changes

2019-12-05 21:33 UTC, ylyubimov commented on task6_3.cpp
> +void Tree::post_order(int param) const{
тут не int должен быть, а функтор
```
template <class TVisitor>
void post_order(TVisitor visit) const {
   visit(node)
}
```

2019-12-08 10:30 UTC, ylyubimov requested changes

2019-12-08 10:30 UTC, ylyubimov commented on task6_3.cpp
> +    visit(root);
Разве это post_order теперь?
visit должен был только заменить вызов std::cout << node->value << std::endl

2019-12-11 07:10 UTC, ylyubimov approved these changes

2019-12-11 07:10 UTC, ylyubimov commented on task6_3.cpp
> +    Visit(){};
можно не писать

2019-12-11 11:04 UTC, mirpulatov commented on task6_3.cpp
> +    Visit(){};
Не очень понял, что именно я могу убрать?

2019-12-11 13:55 UTC, merged