Huffman
mirpulatov/made2019_algo pull request #2
Opened 2019-12-09 05:46 UTC by mirpulatov

2019-12-11 07:09 UTC, ylyubimov requested changes

2019-12-11 07:09 UTC, ylyubimov commented on huffman.cpp
> +} node;
Ты правда здесь inplace переменную node хотел объявить?

2019-12-11 07:09 UTC, ylyubimov commented on huffman.cpp
> +  node* res = new node();
нигде нет удаления этих аллокаций.

2019-12-11 07:09 UTC, ylyubimov commented
Нужна ссылка на контест.

2019-12-15 17:06 UTC, mirpulatov commented
> Нужна ссылка на контест.
https://contest.yandex.ru/contest/15964/run-report/28668899/

2019-12-28 16:44 UTC, ylyubimov approved these changes

2019-12-28 16:44 UTC, ylyubimov commented on huffman.cpp
> +} node;
Вопрос остался

2019-12-29 07:39 UTC, merged