initial commit Prima
mirpulatov/made2019_algo pull request #3
Opened 2019-12-20 09:59 UTC by mirpulatov

2019-12-20 10:00 UTC, mirpulatov commented
https://contest.yandex.ru/contest/16185/run-report/29111937/

2019-12-29 22:54 UTC, ylyubimov requested changes
Пока 4 балла

2019-12-29 22:54 UTC, ylyubimov commented on graph1.cpp
> +    vector<pair<int, int>>* adjList;
Не смешивай контейнеры и указатели

2019-12-29 22:54 UTC, ylyubimov commented on graph1.cpp
> +    ~Graph();
Правило пяти

2019-12-29 22:54 UTC, ylyubimov commented on graph1.cpp
> +    void Prima();
Не по названию алгоритма, а по действию нужно название давать.
+ const

2019-12-29 22:54 UTC, ylyubimov commented on graph1.cpp
> +    vector<pair<int, int>>* adjList;
Переделай на вектор

2019-12-29 22:54 UTC, ylyubimov commented on graph1.cpp
> +    int vertices_count;
adjList.size() => тебе это значение не нужно

2019-12-29 22:54 UTC, ylyubimov commented on graph1.cpp
> +public:
Почему наружу торчит абсолютно все)

2020-01-09 05:29 UTC, closed without merging