Hw8 9
mirpulatov/made2019_algo pull request #5
Opened 2019-12-30 20:28 UTC by mirpulatov

2019-12-30 20:32 UTC, mirpulatov commented
https://contest.yandex.ru/contest/16186/run-report/29200714/
https://contest.yandex.ru/contest/16186/run-report/29355961/
https://contest.yandex.ru/contest/16362/run-report/29350484/
https://contest.yandex.ru/contest/16362/run-report/29362848/

2020-01-07 11:37 UTC, ylyubimov requested changes
Разбей на ПР

2020-01-07 11:37 UTC, ylyubimov commented on rectange.cpp
> +}
Это full-scan, не геохэш

2020-01-07 11:37 UTC, ylyubimov commented on prefix.cpp
> +void prefixFunction(string text, string pattern) {
ссылки должны быть константные

2020-01-07 11:37 UTC, ylyubimov commented on prefix.cpp
> +
Эта задача, ок

2020-01-07 11:37 UTC, ylyubimov commented on template.cpp
> +    void Process(const std::string &text, const std::string &pattern);
Я бы инициализировал шаблоном. А потом бы методом Process уже искал по тексту

2020-01-07 11:37 UTC, ylyubimov commented on template.cpp
> +            std::cout << i << ' ';
ввод вывод только в main'e

2020-01-07 11:37 UTC, ylyubimov commented on template.cpp
> +}
Тут 3 балла пока. Сделай потом отдельный ПР

2020-01-07 11:37 UTC, ylyubimov commented on jarvis.cpp
> +}
Это ок

2020-01-08 04:18 UTC, merged