Prima fixes
mirpulatov/made2019_algo pull request #8
Opened 2020-01-13 05:22 UTC by mirpulatov

2020-01-13 23:06 UTC, ylyubimov requested changes
Нет ссылки на контест

2020-01-14 04:25 UTC, mirpulatov commented
https://contest.yandex.ru/contest/16185/run-report/29111937/

2020-01-14 21:25 UTC, ylyubimov reviewed
Поставил

2020-01-14 21:25 UTC, ylyubimov approved these changes

2020-01-15 05:35 UTC, merged